### PR TITLE
Getting all Favorites in db

### LINKED ISSUE #10: Listing all favorited songs
When sending a `GET` request to the `/api/v1/favorites` endpoint all favorites are queried from the database and a status of `200` with a `json response` such as:
```
[
  {
    "id": 1,
    "title": "We Will Rock You",
    "artistName": "Queen"
    "genre": "Rock",
    "rating": 88
  },
  {
    "id": 2,
    "title": "Careless Whisper",
    "artistName": "George Michael"
    "genre": "Pop",
    "rating": 93
  },
]
```

### LINKED ISSUE #11: Listing all favorited songs Sadpath
When sending a `GET` request to the `/api/v1/favorites` endpoint and no favorites are found then a status of `404` is raised and a `json response` is returned:
```
{
   error: "No favorites were found"
}
```

### PR DESCRIPTION
**Pull request by Not-Zorro**
This closes #11 closes #10 

Tests: Add test happy/sad paths for getting all favorites in the database
Routes: Add `/api/v1/favorites` GET route

### CODE REVIEW

File: app.js [hunk 1]
```diff
@@ -10,10 +10,14 @@ const bodyParser = require("body-parser");
...
 
 app.use('/', indexRouter);
+app.use('/api/v1/favorites', favoritesRouter);
 
-app.set("port", process.env.PORT || 3000);
-app.listen(app.get('port')); console.log(`Running on port ${app.get('port')}`);
+if (process.env.NODE_ENV !== 'test') {
+  app.set("port", process.env.PORT || 3000);
+  app.listen(app.get('port')); console.log(`Running on port ${app.get('port')}`);
+}
```
Comment (cjkelling) [inline app.js]: Fixes problem where the port was busy after running the first test and errored on the following tests. Good work finding this solution.

File: tests/all-favs.spec.js [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+    it('It should respond with all favs in db', async () => {
+      await database('favorites').insert({
+        title: 'We Will Rock You',
+        artistName: 'Queen',
+        genre: 'Rock',
+        rating: 88 }, 'id');
+      await database('favorites').insert({
+        title: 'Careless Whisper',
+        artistName: 'George Michael',
+        rating: 93 }, 'id');
```
Comment (cjkelling) [inline tests/all-favs.spec.js]: Clearing the database before each test and only inserting into the database for the test is a good way of preventing any issues. This should help prevent problems with any future tests.
